spring.application.name=user-service

server.port=8081

#database
spring.datasource.url=jdbc:postgresql://db.naviyfnqtkimwjohuabz.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=benjiro!344
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ADD THESE LINES
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}

#Zipkin
management.tracing.sampling.probability=1

#Actuator
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#resilience4j
resilience4j.circuitbreaker.instances.userBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.userBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.userBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userBreaker.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.userBreaker.max-attempts=5
resilience4j.retry.instances.userBreaker.wait-duration=2s

# resilience4j.ratelimiter.instances.userBreaker.timeout-duration=0
# resilience4j.ratelimiter.instances.userBreaker.limit-for-period=10
# resilience4j.ratelimiter.instances.userBreaker.limit-refresh-period=1s


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=easy-Split
spring.mail.password=1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true