spring.application.name=api-service

server.port=8085

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ADD THESE LINES
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}

#Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

#Gateway
# Gateway configuration
# here i am using only one instance of each service
# if you want to use multiple instances then you need to change the uri to lb://SERVICE-NAME
# id can be unique for each route
spring.cloud.gateway.routes[0].id=user-service
# uri is the url of the service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
# predicates are the conditions that must be met for the route to be applied
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[1].id=group-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/group/**

spring.cloud.gateway.routes[2].id=expence-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/expence/**

spring.cloud.gateway.routes[3].id=user-group-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/user-group/**

logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

#Actuator
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
