spring.application.name=expence-service

server.port=8083

#database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=trues
spring.jpa.platform=org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka.client.service-url.defaultZone=http://eureka-server.railway.internal:8761/eureka/
# diableing eureka client
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ADD THESE LINES
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}

#Zipkin
management.tracing.sampling.probability=1

#Actuator
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#resilience4j
resilience4j.circuitbreaker.instances.expenceBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.expenceBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.expenceBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.expenceBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.expenceBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.expenceBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.expenceBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.expenceBreaker.automatic-transaction-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.expenceBreaker.max-attempts=5
resilience4j.circuitbreaker.instances.expenceBreaker.wait-duration=2s

# resilience4j.ratelimiter.instances.expenceBreaker.timeout-duration=0
# resilience4j.ratelimiter.instances.expenceBreaker.limit-for-period=10
# resilience4j.ratelimiter.instances.expenceBreaker.limit-refresh-period=1s